Repository jenkinsci/packaging, pull requests merged in 2020-04, with the labels that each got.

#132 [WIP] Export public gpg key to file for publishing scripts
  deb/publish/publish.sh
  rpm/publish/publish.sh
  suse/publish/publish.sh
Labels: skip-changelog

#128 Make sure jenkins is really stopped before start in debian init script
  deb/build/debian/jenkins.init
Labels: bug

#137 Windows packaging: invoke signtool to verify the signing results
  msi/build/build.ps1
Labels: skip-changelog

#168 Ignore the msi/build directory
  .gitignore
Labels: chore
