Repository jenkinsci/packaging, pull requests merged in 2022-03, with the labels that each got.

#290 Regenerate test key
  credentials/README.md
  credentials/sandbox.gpg
  credentials/test.ascii.key
  credentials/test.gpg
  credentials/test.secret.gpg
Labels: chore

#291 Use systemd and other updates on stable-2.332 branch
  credentials/README.md
  credentials/sandbox.gpg
  credentials/test.ascii.key
  credentials/test.gpg
  credentials/test.secret.gpg
  deb/build/build.sh
  deb/build/debian/jenkins.default
  deb/build/debian/jenkins.install
  deb/build/debian/jenkins.postinst
  molecule/default/Dockerfile.j2
  molecule/default/install-deb.yml
  molecule/default/install-rpm.yml
  molecule/default/install-suse.yml
  molecule/default/verify.yml
  rpm/build/SPECS/jenkins.spec
  rpm/build/build.sh
  suse/build/SPECS/jenkins.spec
  suse/build/build.sh
  systemd/jenkins.service
  systemd/jenkins.sh
  systemd/migrate.sh
Labels: ready-for-merge

#294 Delete unused release drafter config
  .github/release-drafter.yml
Labels: chore

#296 [JENKINS-68007] Prefer `--httpPort` from `JENKINS_ARGS` over `HTTP_PORT` when the two differ
  systemd/migrate.sh
Labels: bug

#298 Add preview support for Java 17
  systemd/jenkins.sh
Labels: enhancement, squash-merge-me

#300 Remove references to `limits.conf`
  systemd/jenkins.service
Labels: documentation
