Repository jenkinsci/packaging, pull requests merged in 2022-09, with the labels that each got.

#329 `git status` is not clean
  .gitattributes
Labels: bug

#335 [JENKINS-69570] Java version check incorrect in `/etc/init.d/jenkins`
  deb/build/debian/jenkins.init
  systemd/jenkins.sh
Labels: bug

#337 [JENKINS-69638] Support HTTP/2 without custom `--extraLibFolder` configuration
  systemd/jenkins.service
Labels: documentation

#338 Test Red Hat Enterprise Linux 9 derivatives
  molecule/default/molecule.yml
Labels: test
