Repository jenkinsci/packaging, pull requests merged in 2023-07, with the labels that each got.

#418 Fix RPM tests
  molecule/default/install-rpm.yml
Labels: test

#409 RPM: Remove System V initialization script
  rpm/build/SOURCES/jenkins.init.in
  rpm/build/SOURCES/jenkins.logrotate
  rpm/build/SOURCES/jenkins.sysconfig.in
  rpm/build/SPECS/jenkins.spec
Labels: removed

#420 Update documentation
  templates/header.redhat.html
Labels: documentation

#421 Use Java 17 for tests and documentation
  molecule/default/install-deb.yml
  molecule/default/install-rpm.yml
  molecule/default/install-suse.yml
  molecule/servlet/molecule.yml
  systemd/jenkins.service
  templates/header.debian.html
  templates/header.opensuse.html
  templates/header.redhat.html
Labels: test, documentation
