Repository jenkinsci/packaging, pull requests merged in 2024-06, with the labels that each got.

#466 Downgrade `requests` to last working version
  requirements.txt
Labels: chore

#468 Remove EOL platforms
  molecule/default/molecule.yml
Labels: removed

#477 Drop Debian 10 support
  molecule/default/install-deb.yml
  molecule/default/molecule.yml
Labels: enhancement

#475 Fix incorrect conditional in Java 17 version check
  msi/build/jenkins.wxs
  msi/build/jenkins_en-US.wxl
Labels: bug

#474 Include 2.463 in docs as first weekly to require Java 17 or newer
  rpm/build/SPECS/jenkins.spec
  suse/build/SPECS/jenkins.spec
  templates/base.html
  templates/header.war.html
Labels: documentation

#478 Test with Ansible 9.7.0
  requirements.txt
Labels: test

#476 Remove Java 11 from MSI installer (Windows)
  msi/build/jenkins.wxs
  msi/build/jenkins_en-US.wxl
Labels: enhancement

#480 Test on Ubuntu 24.04 LTS (Noble Numbat)
  molecule/default/molecule.yml
Labels: test

#481 Test on openSUSE Leap 15.5 and 15.6
  molecule/default/molecule.yml
Labels: test

#482 Test on Fedora 40
  molecule/default/molecule.yml
Labels: test

#483 Test on EuroLinux 9
  molecule/default/molecule.yml
Labels: test
